apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: up9bujccb-dotnet-basic
  janus-idp.io/tekton: up9bujccb-dotnet-basic
  backstage.io/kubernetes-id: up9bujccb-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: up9bujccb-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
